# Jupyter Book settings

title: "A short intro to web frontend"
author: Thierry Parmentelat
logo: media/logo.png

repository:
  url: https://github.com/ue22-p21/web-intro
  branch: main
  path_to_book: notebooks

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes

###

only_build_toc_files: true

exclude_patterns:
  - "**/.teacher/*"

execute:
  execute_notebooks: cache
  exclude_patterns:
    - "**/*-corrige*"
    - "**/.teacher/*"

parse:
  myst_enable_extensions:
    - html_image    # for raw <img> tags in markdown
    - dollarmath    # for mathjax
    - strikethrough

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    html_show_copyright: false
    # not quite convincing but...
    html_extra_path: ['media']
